name: Move Triaged Issues to Grab n Go

on:
  issues:
    types: [labeled]

permissions:
  issues: read
  contents: read  # Required for some actions

jobs:
  add-to-grab-n-go:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'triaged'
    steps:
      - name: Generate app token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
      - name: Add to Grab n Go Board
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/midnightntwrk/projects/37
          github-token: ${{ steps.generate-token.outputs.token }}

  remove-from-community:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'triaged'
    steps:
      - name: Generate app token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
      - name: Remove from Community Board
        uses: monry/actions-delete-issue-from-project@v2
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          project-owner: midnightntwrk
          project-number: 36
          issue-repository: ${{ github.repository }}
          issue-number: ${{ github.event.issue.number }}