name: Move Triaged Issues

on:
  issues:
    types: [labeled]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'triaged'
    
    # Permissions are now defined at the job level
    permissions:
      issues: write
      projects: write
      
    steps:
      - name: Add to Grab n Go Board
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/midnightntwrk/projects/37
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove from Community Board
        uses: monry/actions-delete-issue-from-project@v2.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-owner: midnightntwrk
          project-number: 36
          issue-repository: ${{ github.repository }}
          issue-number: ${{ github.event.issue.number }}