name: Triage Move to Grab n Go
on:
  issues:
    types: [labeled]
permissions:  # Grants necessary scopes to GITHUB_TOKEN for project mutations
  projects: write
  issues: read
jobs:
  add-to-grab-n-go:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'triaged'
    steps:
      - name: Add to Grab n Go Board and Remove from Community Board
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}  # Uses built-in GITHUB_TOKEN with granted permissions
          script: |
            const grabNGoProjectId = 'PVT_kwDOC7x9W84A-fjK';  # Grab n Go Board GraphQL ID (project 37)
            const communityBoardProjectId = 'PVT_kwDOC7x9W84A90_s';  # Community Board GraphQL ID (project 36)
            const contentId = context.payload.issue.node_id;

            // Add issue to Grab n Go Board
            const addMutation = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `;
            await github.graphql(addMutation, {
              projectId: grabNGoProjectId,
              contentId: contentId
            });

            // Remove issue from Community Board
            const removeMutation = `
              mutation($projectId: ID!, $contentId: ID!) {
                deleteProjectV2Item(input: {projectId: $projectId, itemId: $contentId}) {
                  deletedItemId
                }
              }
            `;
            await github.graphql(removeMutation, {
              projectId: communityBoardProjectId,
              contentId: contentId
            });